# Generated by Django 2.2.14 on 2024-02-11 20:04

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=10)),
                ('upper', models.FloatField(blank=True, null=True)),
                ('lower', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.CheckConstraint(check=models.Q(('lower__isnull', False), ('upper__isnull', False), _connector='OR'), name='lower_or_upper_not_both_null'),
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.CheckConstraint(check=models.Q(upper__gt=django.db.models.expressions.F('lower')), name='upper_greater_than_lower'),
        ),
    ]
